from datasetsModule.analyseDatasets import AnalyseDataset

analyser : AnalyseDataset = AnalyseDataset()

analyser.analyseDataset("ET", 32)
analyser.analyseDataset("covid19Deaths", 32)
analyser.analyseDataset("electricityUCI", 32)
analyser.analyseDataset("fredMd", 32)
analyser.analyseDataset("huaweiCloud", 32)
analyser.analyseDataset("m4-monthly", 32)
analyser.analyseDataset("nn5", 32)
analyser.analyseDataset("power", 32)
analyser.analyseDataset("traffic", 32)

analyser.analyseDataset("ET", 32)
analyser.analyseDataset("covid19Deaths", 32)
analyser.analyseDataset("electricityUCI", 32)
analyser.analyseDataset("fredMd", 32)
analyser.analyseDataset("huaweiCloud", 32)
analyser.analyseDataset("m4-monthly", 32)
analyser.analyseDataset("nn5", 32)
analyser.analyseDataset("power", 32)
analyser.analyseDataset("traffic", 32)

analyser.analyseDataset("ET", 64)
analyser.analyseDataset("covid19Deaths", 64)
analyser.analyseDataset("electricityUCI", 64)
analyser.analyseDataset("fredMd", 64)
analyser.analyseDataset("huaweiCloud", 64)
analyser.analyseDataset("m4-monthly", 64)
analyser.analyseDataset("nn5", 64)
analyser.analyseDataset("power", 64)
analyser.analyseDataset("traffic", 64)

analyser.analyseDataset("ET", 128)
analyser.analyseDataset("covid19Deaths", 128)
analyser.analyseDataset("electricityUCI", 128)
analyser.analyseDataset("fredMd", 128)
analyser.analyseDataset("huaweiCloud", 128)
analyser.analyseDataset("m4-monthly", 128)
analyser.analyseDataset("nn5", 128)
analyser.analyseDataset("power", 128)
analyser.analyseDataset("traffic", 128)